### ISSUE TITLE
Viruses

### ISSUE THREAD

**Issue by ombhatt2** [RidwanA123/MEMEZ#2]
This can cause virus!

**Comment by Luke-zhang-04** [comment]
And you have a fork of it!

![](https://user-images.githubusercontent.com/55749227/109224217-a78a0f80-7789-11eb-90ef-c59e3b9888ef.png)

https://github.com/Omcodez1503/MEMEZ

**Comment by n5q** [comment]
Many such cases!

**Comment by RidwanA123** [comment]
> This can cause virus!

Reporting if you create another issue one more time

**Comment by ombhatt2** [comment]
YEAH its to test and see if it has a virus and indeed it can give the trojan virus! DELETE NOW

**Comment by RidwanA123** [comment]
> YEAH its to test and see if it has a virus and indeed it can give the trojan virus! DELETE NOW

Then don't open it?

**Comment by ombhatt2** [comment]
Viruses are bad you should make this more secure

**Comment by RidwanA123** [comment]
> Viruses are bad you should make this more secure

Ok. Now run along...

**Comment by ombhatt2** [comment]
wdym run along?

**Comment by RidwanA123** [comment]
> wdym run along?

Stop coming back here and commenting.

**Comment by ombhatt2** [comment]
anyways I had to say what I had to say!

**Comment by RidwanA123** [comment]
> anyways I had to say what I had to say!

Alright, now buzz off.

**Comment by pranjaln16** [comment]
> anyways I had to say what I had to say!

yo let ridwan do his own things for fucks sake

**Comment by RidwanA123** [comment]
> > anyways I had to say what I had to say!
> 
> yo let ridwan do his own things for fucks sake

like spamming my github?

**Comment by ombhatt2** [comment]
Please dont swear, thank you, and give credit!

**Comment by pranjaln16** [comment]
> Please dont swear, thank you, and give credit!

He did give credit in the README Section.

**Comment by RidwanA123** [comment]
It's meant to be run on a VM and it ain't destructive except the MBR...

**Comment by ombhatt2** [comment]
ok ridvan

**Comment by Omcodez1503** [comment]
> And you have a fork of it!
> 
> ![](https://user-images.githubusercontent.com/55749227/109224217-a78a0f80-7789-11eb-90ef-c59e3b9888ef.png)
> 
> https://github.com/Omcodez1503/MEMEZ

Ya because I need to

**Comment by RidwanA123** [comment]
> ok ridvan

?

**Comment by ombhatt2** [comment]
Why are you commenting again?

**Comment by Luke-zhang-04** [comment]
Idk Om, why are you commenting again?

**Comment by RidwanA123** [comment]
Why do you keep creating issues. Read Description lol.
